// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG6NSYRS7PjI8vENXu96aJDoRxsWdksfc',
    appId: '1:814893140977:web:68c325955950b88cc65250',
    messagingSenderId: '814893140977',
    projectId: 'telegochat',
    authDomain: 'telegochat.firebaseapp.com',
    storageBucket: 'telegochat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNgKVuBWHev4T7zDyhIPhCDnFVyl2tyLU',
    appId: '1:814893140977:android:e1a27003c1dc77a4c65250',
    messagingSenderId: '814893140977',
    projectId: 'telegochat',
    storageBucket: 'telegochat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRVn6Azpbaw2RfBQ7vY3riiYbhtHNGsc',
    appId: '1:814893140977:ios:a49145b753a3161bc65250',
    messagingSenderId: '814893140977',
    projectId: 'telegochat',
    storageBucket: 'telegochat.appspot.com',
    iosBundleId: 'com.example.telegoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyRVn6Azpbaw2RfBQ7vY3riiYbhtHNGsc',
    appId: '1:814893140977:ios:59d030cdd2260a22c65250',
    messagingSenderId: '814893140977',
    projectId: 'telegochat',
    storageBucket: 'telegochat.appspot.com',
    iosBundleId: 'com.example.telegoChat.RunnerTests',
  );
}
